from tkinter import*
from tkinter import messagebox
root=Tk()

filename = PhotoImage(file ="C:\\Users\\Shashu\\Desktop\\labf.png")
background_label = Label(root, image=filename)
background_label.place(x=0, y=0, relwidth=1, relheight=1)
root.geometry("1350x800+0+0")
label1=Label(root,text="AVALIABLE BOOKS:-",font=("algerian",30),fg="black",bg="violet",bd=5)
label2=Label(root,text="CHOOSE SUBJECT",font=("Castellar",15,"underline"),fg="blue",bd=5)
label1.grid(row=0,column=0)
label2.grid(row=1,column=1,padx=120)
menubutton1=Menubutton(root,text="Mathematics-II",font=15,fg="red",bg="sky blue",bd=5,relief=RAISED)
menubutton1.grid(row=2,column=0,padx=30,pady=60)
maths=Menu(menubutton1)
menubutton1["menu"]=maths
maths.add_checkbutton(label="Engg. Maths-2 By G.V Kumbhojkar")
maths.add_checkbutton(label="Engg. Maths-2 By N.H.Dubey")
maths.add_checkbutton(label="Engg. Maths-2 Tech-Max")
maths.add_checkbutton(label="Engg. Maths-2 Easy Solution By Vikas Sharma")
maths.add_checkbutton(label="Concept Of Maths-II")
menubutton2=Menubutton(root,text="C Programing",font=15,fg="red",bd=5,bg="sky blue",relief=RAISED)
menubutton2.grid(row=2,column=1,padx=10,pady=60)
cp=Menu(menubutton2)
menubutton2["menu"]=cp
cp.add_checkbutton(label="ANSI C")
cp.add_checkbutton(label="C Programing By Willey India")
cp.add_checkbutton(label="Let us C")
cp.add_checkbutton(label="Programing In C")
cp.add_checkbutton(label="Introduction To C Programing")
menubutton3=Menubutton(root,text="Engg. Drawing",font=15,fg="red",bd=5,bg="sky blue",relief=RAISED)
menubutton3.grid(row=2,column=3,pady=60,padx=40)
eg=Menu(menubutton3)
menubutton3["menu"]=eg
eg.add_checkbutton(label="Engg. Drawing By S Chand")
eg.add_checkbutton(label="Engg. Graphics By N.H.Dubey")
eg.add_checkbutton(label="Engg. Drawing By N.D Bhatt")
menubutton=Menubutton(root,text="",bg="black")
menubutton.grid(row=2,column=2,pady=60,padx=40)
menubutton4=Menubutton(root,text="Engg. Chemistry-II",font=15,bd=5,bg="sky blue",fg="red",relief=RAISED)
menubutton4.grid(row=5,column=0,padx=30,pady=60)
ec=Menu(menubutton4)
menubutton4["menu"]=ec
ec.add_checkbutton(label="Engg. Chemistry By Shashi Chawla")
ec.add_checkbutton(label="Engg. Chemistry Wiley India")
ec.add_checkbutton(label="Applied Chemistry By S.Chand")
ec.add_checkbutton(label="Applied Chemistry By Dara & Dara")
ec.add_checkbutton(label="Engg. Chemistry Jain & Jain")
menubutton5=Menubutton(root,text="Engg. Physics-II",font=15,bd=5,fg="red",bg="sky blue",relief=RAISED)
menubutton5.grid(row=5,column=1,padx=10,pady=60)
ep=Menu(menubutton5)
menubutton5["menu"]=ep
ep.add_checkbutton(label="Concept Of Modern Physics")
ep.add_checkbutton(label="Engg. Physics By R.K.Gaur")
ep.add_checkbutton(label="Applied Physics 2-tech max")
ep.add_checkbutton(label="A TextBook Of Engg. Physics-II")
ep.add_checkbutton(label="Technical Physics-II")
menubutton6=Menubutton(root,text="Communication Skills",font=15,bd=5,fg="red",bg="sky blue",relief=RAISED)
menubutton6.grid(row=5,column=3,pady=60,padx=40)
em=Menu(menubutton6)
menubutton6["menu"]=em
em.add_checkbutton(label="Mastering Communication")
em.add_checkbutton(label="Business Communication")
em.add_checkbutton(label="Effective Technical Communication")
em.add_checkbutton(label="Communication Skills By Sangeeta Sharma")
menubuttona=Menubutton(root,text="",bg="black")
menubuttona.grid(row=3)
menubuttonb=Menubutton(root,text="",bg="black")
menubuttonb.grid(row=4)
root.mainloop()
